# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170518_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
